# Generated by Django 5.0.6 on 2024-06-24 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=200)),
                ('inicia', models.DateField()),
            ],
        ),
    ]
